### ISSUE TITLE
1.21.3 issue

### ISSUE THREAD

**Issue by PaladinFallen** [Sideways-Sky/MultiMine#2]
To reproduce: This error appears every time a player tries to mine a block, also when a player mines a block they mine it extremely faster than normal.

[19:23:20] [Server thread/ERROR]: Could not pass event BlockBreakProgressUpdateEvent to MultiMine v1.3
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/CraftWorld
	at MultiMine-1.3.jar/net.sideways_sky.multimine.DamagedBlock.sendPacket(DamagedBlock.java:83) ~[MultiMine-1.3.jar:?]
	at MultiMine-1.3.jar/net.sideways_sky.multimine.DamagedBlock.sendPacket(DamagedBlock.java:80) ~[MultiMine-1.3.jar:?]
	at MultiMine-1.3.jar/net.sideways_sky.multimine.Events.onBlockBreakProgressUpdate(Events.java:47) ~[MultiMine-1.3.jar:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:41) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerLevel.destroyBlockProgress(ServerLevel.java:1668) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.level.ServerPlayerGameMode.incrementDestroyProgress(ServerPlayerGameMode.java:170) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.level.ServerPlayerGameMode.tick(ServerPlayerGameMode.java:158) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:994) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1305) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1489) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:812) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:794) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1875) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1664) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1329) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-71-0cc7bd4]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Sideways-Sky** [comment]
Unable to reproduce. I need a lot more context to replicate this issue.

**Comment by PaladinFallen** [comment]
Issue: 

- Have the latest version of paper server and the latest version of fabric running 1.21.3
- Have the latest version of mulitmine
- Have player mine, block breaks faster than normal

Plugins:
[List](https://pastebin.com/Eziq3cqJ)

Error:
[Errors with debug on](https://pastebin.com/Yznyqbsw)

**Comment by Sideways-Sky** [comment]
So you use a hybrid server architecture of paper and fabric? What server architecture are you using?

**Comment by PaladinFallen** [comment]
No, I'm running a Paper Server 1.21.3 Build 73 on Java 21, and the client is a Fabric build 16.9, version 1.21.3...

**Comment by Sideways-Sky** [comment]
Try v1.3.1 reopen if not fixed
